apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: basketball-league-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: adminer
  template:
    metadata:
      labels:
        service: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ADMINER_DEFAULT_SERVER
              valueFrom:
                configMapKeyRef:
                  name: basketball-league-tracker-config
                  key: DB_HOST