apiVersion: v1
kind: ConfigMap
metadata:
  name: basketball-league-tracker-config
  namespace: basketball-league-tracker
  labels:
    app.kubernetes.io/name: basketball-league-tracker
data:
  POSTGRES_DB: basketball
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: basketball
  SEED_DATA: "true"