apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: basketball-league-tracker
spec:
  clusterIP: None
  selector:
    service: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432